app = "torch"
primary_region = "iad"

[mounts]
source = "data"
destination = "/data"
initial_size = "20gb"  

[vm]
size = "performance-4x" 

[machines]
min_machines_running = 1
auto_start_machines = true
auto_stop_machines = false