app = "torch"
primary_region = "ord"
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
# vm.size = "a10"

# [deploy]
# org = "your-organization-slug"

[mounts]
source = "data"
destination = "/data"
initial_size = "10gb"  

# [http_service]
# internal_port = 8080
# force_https = true
# auto_stop_machines = false
# auto_start_machines = true
# min_machines_running = 1

[vm]
size = "performance-2x" 

[machines]
min_machines_running = 1
auto_start_machines = true
auto_stop_machines = false