apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-pod
      image: h.nodestaking.com/mlx/mnist:1
      # image: h.nodestaking.com/mlx/mnist:8a0446c5-86e6-427b-b5a5-cc40d6da94b5
      # imagePullPolicy: Always
  # imagePullSecrets:
  #   - name: ghcr-secret
      # env:
      #   - name: PDM_USE_VENV
      #     value: "true"
      #   - name: PDM_VENV_IN_PROJECT
      #     value: "true"
      #   - name: PATH
      #     value: "/app/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      # command: ["/bin/sh", "-c", "pdm install --prod --frozen-lock && exec pdm run main.py"]

      # h.nodestaking.com/mlx/mnist:8a0446c5-86e6-427b-b5a5-cc40d6da94b5